# Generated by Django 5.0.14 on 2026-08-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_categorymodel_registerusermodel_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='BookingModel',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='ServiceModel',
        ),
    ]
