# Generated by Django 5.0.14 on 2026-08-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_servicemodel_category_delete_bookingmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerusermodel',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
