# Generated by Django 5.0.14 on 2026-08-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_registerusermodel_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerusermodel',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('engineer', 'Engineer')], default='customer', max_length=20),
        ),
    ]
