# Generated by Django 5.0.14 on 2026-08-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_registerusermodel_role'),
        ('services', '0002_alter_bookingmodel_engineer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EngineerProfile',
        ),
    ]
