# Generated by Django 5.0.14 on 2026-08-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_bookingmodel_engineer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
