# Generated by Django 5.0.14 on 2026-08-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerprofile',
            name='experience',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='professional_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
